spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: 12
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    # 초기 데이터베이스 등록
  sql:
    init:
      mode: always
      data-locations: classpath:/sql/init.sql
image:
  upload:
    dir: D:/userimg_img/


  #secret_key
jwt:
  secret: agRot5OxbyIAgR9wjQr4Woh4WJr08Kq2995C7882483FF7C7C354249F6B6F7
